version: 2
seeds:
  - name: employees
    description: csv file implementation
    columns:
      - name: employee_id
        tests:
          - unique
          - not_null
              
              